name: Bug report
description: Report a reproducible problem in GitCDN
title: "bug: "
labels:
  - bug
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened?
      placeholder: A clear and concise description of the bug.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Provide exact steps.
      placeholder: |
        1. Go to ...
        2. Click ...
        3. See error ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: OS, browser, Node version, deployment target.
      placeholder: macOS 14, Chrome 123, Node 22, Vercel Hobby
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Logs / screenshots
      description: Add relevant output, stack traces, or screenshots.
    validations:
      required: false
